// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrxysmouF59N1z85aFV9pyEdBRaP1oWKs',
    appId: '1:1086229509296:web:cf9a73151fabd29941f775',
    messagingSenderId: '1086229509296',
    projectId: 'be3ly-46eb8',
    authDomain: 'be3ly-46eb8.firebaseapp.com',
    storageBucket: 'be3ly-46eb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrAH-k-U0B4k7-XIYdAPZMAdS25hK464c',
    appId: '1:1086229509296:android:6b52861c2faa1e3241f775',
    messagingSenderId: '1086229509296',
    projectId: 'be3ly-46eb8',
    storageBucket: 'be3ly-46eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAj36CgbLBxJSCTknGTzdrzK7tBV_zzqs',
    appId: '1:1086229509296:ios:f2f42455384dac2341f775',
    messagingSenderId: '1086229509296',
    projectId: 'be3ly-46eb8',
    storageBucket: 'be3ly-46eb8.appspot.com',
    iosBundleId: 'com.example.be3lyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAj36CgbLBxJSCTknGTzdrzK7tBV_zzqs',
    appId: '1:1086229509296:ios:32555acd78484f0341f775',
    messagingSenderId: '1086229509296',
    projectId: 'be3ly-46eb8',
    storageBucket: 'be3ly-46eb8.appspot.com',
    iosBundleId: 'com.example.be3lyapp.RunnerTests',
  );
}
